apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azkvkdqf5-go-gitops
  description: This is GitOps manifest for azkvkdqf5-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=azkvkdqf5-go
    backstage.io/kubernetes-id: azkvkdqf5-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: azkvkdqf5-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:azkvkdqf5-go
